version: '3'
services:
  ec:
    image: ghcr.io/super-protocol/sp-execution-controller:latest
    command: npm run start
    env_file:
      - ./.env
  mongodb:
    image: mongo:7.0.5
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
